
### RUTA ###
@api = http://localhost:3000/empleados

@api2 = http://localhost:3000/login

### OBTENER TODOS LOS EMPLEADOS ACTIVOS ###
GET {{ api }}


### AGREGAR NUEVO EMPLEADO ###
POST {{ api }}
Content-Type: application/json

{
    "nombreEmpleado": "Martín",
    "puesto": "jefe",
    "sueldo": 100,
    "correo": "prueba.test@ganfer.com",
    "celular": "3",
    "usuario": "martin",
    "password": "123",
    "isAdmin": 1
}


### BUSCAR EMPLEADO POR ID
GET {{ api }}/2aa773ef-962a-4967-8b7f-1dcf6f1a24c5


### EDITAR USUARIO POR ID ###
PUT {{ api }}/
Content-Type: application/json

{
    "nombreEmpleado": "empleado editado",
    "puesto": "1",
    "sueldo": 1,
    "correo": "1",
    "celular": "1",
    "usuario": "1",
    "password": "1",
    "isAdmin": "1"
}


### ELIMINAR EMPLEADO ###
DELETE {{ api }}/


### LOGIN ###
POST {{ {{api2}} }}
Content-Type: application/json

{
    "usuario": "aldo",
    "password": "123"
}